function  obj = initRapidSettings(obj)
% INITRAPIDSETTINGS this function is meant to create a default
% RAPIDSETTINGS object
%   Detailed explanation goes here
obj.experimentSettings=struct('tf',1,'ts',0.1,'p_min',[],'p_max',[],'p_0',[],...
    'cost_type',1,'objective_weights',1,'t_fitness_start',0,...
    'integrationMethod','ode45','maxIterations',100,'solverMode','Simulink',...
    'pathToSimulinkModel','','modelName','','blockName','','scopeName','simout',...
    'verbose',1,'displayMode','hide','saveHist',0,'timeOut',2,...
    'pathToFmuModel','','outputPostProcessing','','optimizationAlgorithm','pso',...
    'pathToFMUModel','');
obj.experimentData = struct('pathToInData','','expressionInData','',...
    'expressionInDataTime','','referenceOutdata',[],'referenceTime',[],...
    'pathToReferenceData','','expressionReferenceTime','','expressionReferenceData','');
obj.psoSettings=struct('w',0.25,'self_coeff',0.25,'social_coeff',0.25,...
    'nRandMin',8,'nb_particles',8,'fitnessStopRatio',1e-5,...
    'kick_multiplier',0.002,'w_min', 0.01, 'w_max',1,'method','PSO');
obj.gaSettings=struct('nbCromosomes',40,'nbCroossOver1',10,'nbCroossOver2',10,...
    'nbMutations',10,'nbReproduction',10,'limit',10,'fitnessStopRatio',1e-5,...
    'headSize1',5,'headSize2',5,'headSize3',3,'nbReinjection',5,'nRandMin',10, ...
    'p0s', [],'storeData',0);    
obj.combiSettings=struct('firstMethod','pso','psoExtOptions','nm','secondMetod','nm'); 
obj.naiveSettings=struct('tolerance1',1e-4,'tolerance2',1e-7,'iterations',1,'iterations2',1,'iterations3',1);
obj.knitroSettings=struct('path2Knitro','','knOptionsFile','', ...
    'knOptions','optimset(''Algorithm'',''active-set'',''TolFun'',1e-6,''TolX'',1e-6);');
obj.nmSettings='optimset(''fminsearch'')';   
obj.cgSettings='optimset(optimset(''fminunc''),''FinDiffType'',''central'',''TolX'',1e-6,''LargeScale'',''off'')';
obj.psoExtSettings='psoptimset'; 
obj.gaExtSettings='gaoptimset';
obj.fminconSettings='optimset(''FinDiffRelStep'',0.1)';
obj.pfSettings=struct('nb_particles', 100,'prune_threshold', 0.1,'kernel_sigma',1);
obj.resultData=[];
obj.fmuOutputNames={''};
obj.parameterNames={''};
obj.fmuInputNames={''};
obj.version=1.41;
end

